language: node_js
node_js:
  - 10

cache:
  npm: true
  directories:
    - ~/.cache

script:
  - npm run build
  - npm run test
  - echo $PATH
  - whereis cypress
  - cypress install
  - npm run ci:e2e